
# EXAMPLE >>>>>>>>>>>>>>>>>>>>>>>>>
language: objective-c
cache: bundler
git:
  depth: 10000

before_install:
  - echo secure: "ElFqRXe1UiAAZkbuanfXU62MFOxDp/9kpJs+LdrRtAY3DsgP1+76jYAtb2vPhxylzHq699P35cJUMQZJvgBHu78f9U1NgKk7OkgXAOcvrkLXYsSYlX/UcE1+HdRv/Rdkba9lTWgduUDlDUhVPof1zWq8BiwBsimbCEb5UjZAFeY="
  - echo "$SECRET_VAR"
  - echo "$(git rev-list HEAD --count)"
  - echo "$(git rev-list --count)"
  - echo "$(git rev-parse HEAD -count)"
  - git=`sh /etc/profile; which git`
  - build_num=`"$git" rev-list --all |wc -l` # we count for all branches
  - echo "$build_num"
  - git rev-list --all
  
  - buildNumber=$(git rev-list HEAD --count)
  - echo "Build number= $buildNumber"
  
  - brew update && brew install phantomjs # sigh dependecy
  - gem install sigh

before_script:
  - ./Scripts/add-key.sh
  
  - PROFILE_UDID=$(./Scripts/profileAnalyzer.rb "$XC_PROFILE_PATH/$PROFILE_NAME.mobileprovision")
  - echo $PROFILE_UDID
  - ls "$XC_PROFILE_PATH"

script:
 - echo ${PROFILE_UDID}
 - xctool -project TravisExample.xcodeproj -scheme TravisExample -configuration $XC_CONFIGURATION -sdk iphoneos clean build OBJROOT=$PWD/build SYMROOT=$PWD/build PROVISIONING_PROFILE=${PROFILE_UDID} CODE_SIGN_IDENTITY="$DEVELOPER_NAME" HOCKEY_APP_ID=$HOCKEY_APP_ID 

after_script:
- ./scripts/remove-key.sh
after_success:
- ./scripts/sign-and-upload.sh
env:
  global:
  - APP_NAME="Travis"
  - DEVELOPER_NAME=""
  - PROFILE_NAME="TravisExample"
  - INFO_PLIST="TravisExample/TravisExample-Info.plist"
  - BUNDLE_DISPLAY_NAME="Travis Example CI"
  - BUNDLE_IDENTIFIER="com.example.Travis"
   
  - KEYCHAIN_NAME="ios-build"
  - TEAM_ID="4S4VJWAS6R"
  - USER_ID="glogera@gmail.com"
  - XC_CONFIGURATION="Release"
  - XC_SDK="iphoneos"
  - XC_PROFILE_PATH="$HOME/Library/MobileDevice/Provisioning Profiles"

