
# EXAMPLE >>>>>>>>>>>>>>>>>>>>>>>>>
language: objective-c
cache: bundler

before_install:
  - brew update && brew install phantomjs # sigh dependecy
  - gem install sigh

before_script:
  - security create-keychain -p travis $KEYCHAIN_NAME.keychain
  - security import ./Scripts/certs/distEnterprise.p12 -k ~/Library/Keychains/$KEYCHAIN_NAME.keychain -P $P12_PASSWORD -T /usr/bin/codesign
  - security import ./Scripts/certs/apple.cer -k ~/Library/Keychains/$KEYCHAIN_NAME.keychain -T /usr/bin/codesign
  
  - mkdir -p "$XC_PROFILE_PATH"
  - DELIVER_PASSWORD="$APPLE_PASSWORD" sigh -a 'com.example.Travis' -u $USER_ID -t $TEAM_ID -n "TRAVIS-$PROFILE_NAME" -o "$XC_PROFILE_PATH" -f $PROFILE_NAME.mobileprovision

  - PROFILE_UDID=$(./Scripts/profileAnalyzer.rb "$XC_PROFILE_PATH/$PROFILE_NAME.mobileprovision")
  - echo $PROFILE_UDID
  - ls "$XC_PROFILE_PATH"

script:
 - echo ${PROFILE_UDID}
 - xctool clean build -project TravisExample.xcodeproj -scheme HallBETA -configuration $XC_CONFIGURATION -sdk iphoneos OBJROOT=$PWD/build SYMROOT=$PWD/build PROVISIONING_PROFILE=${PROFILE_UDID} HOCKEY_APP_ID=$HOCKEY_APP_ID 

after_script:
- ./scripts/remove-key.sh
after_success:
- ./scripts/sign-and-upload.sh
env:
  global:
  - APP_NAME="TravisExample"
  - 'DEVELOPER_NAME="iPhone Distribution: Mattes Groeger"'
  - PROFILE_NAME="TravisExample_Ad_Hoc"
  - INFO_PLIST="TravisExample/TravisExample-Info.plist"
  - BUNDLE_DISPLAY_NAME="Travis Example CI"
  - BUNDLE_IDENTIFIER="com.example.Travis"
   
  - KEYCHAIN_NAME="ios-build"
  - TEAM_ID="4S4VJWAS6R"
  - USER_ID="glogera@gmail.com"
  - XC_CONFIGURATION="Release"
  - XC_SDK="iphoneos"
  - XC_PROFILE_PATH="$HOME/Library/MobileDevice/Provisioning Profiles"

